export default {
  wiki: [
    'testing',
    // {
    //   type: 'category',
    //   label: 'Getting Started',
    //   link: {
    //     type: 'generated-index'
    //   },
    //   items: [
    //     'getting-started/what-is-this-modpack-about',
    //     'getting-started/system-requirements',
    //     'getting-started/installation-guide',
    //     'getting-started/performance-tips',
    //     'getting-started/customizations',
    //     'getting-started/helpful-commands',
    //     'getting-started/mod-list',
    //     'getting-started/version-history'
    //   ]
    // },
    // {
    //   type: 'category',
    //   label: 'The Central Questions',
    //   link: {
    //     type: 'generated-index'
    //   },
    //   items: [
    //     {
    //       type: 'category',
    //       label: 'Who Are You?',
    //       link: {
    //         type: 'generated-index'
    //       },
    //       items: [
    //         {
    //           type: 'category',
    //           label: 'Chapters',
    //           link: {
    //             type: 'generated-index'
    //           },
    //           items: [
    //             {
    //               type: 'category',
    //               label: 'Chapter 1',
    //               link: {
    //                 type: 'generated-index'
    //               },
    //               items: [
    //                 {
    //                   type: 'category',
    //                   label: 'Milestones',
    //                   link: {
    //                     type: 'generated-index'
    //                   },
    //                   items: [
    //                     {
    //                       type: 'category',
    //                       type: 'autogenerated',
    //                       dirName: 'questions/who/chapters/chapter-1/milestones'
    //                     }
    //                   ]
    //                 },
    //                 {
    //                   type: 'category',
    //                   label: 'Mechanics',
    //                   link: {
    //                     type: 'generated-index'
    //                   },
    //                   items: [
    //                     {
    //                       type: 'category',
    //                       type: 'autogenerated',
    //                       dirName: 'questions/who/chapters/chapter-1/mechanics'
    //                     }
    //                   ]
    //                 },
    //                 'questions/who/chapters/chapter-1/desperate-measures',
    //                 'questions/who/chapters/chapter-1/journal-entries',
    //                 'questions/who/chapters/chapter-1/cold-nightmare'
    //               ]
    //             },
    //             {
    //               type: 'category',
    //               label: 'Chapter 2',
    //               link: {
    //                 type: 'generated-index'
    //               },
    //               items: [
    //                 {
    //                   type: 'category',
    //                   label: 'Milestones',
    //                   link: {
    //                     type: 'generated-index'
    //                   },
    //                   items: [
    //                     {
    //                       type: 'category',
    //                       type: 'autogenerated',
    //                       dirName: 'questions/who/chapters/chapter-2/milestones'
    //                     }
    //                   ]
    //                 },
    //                 {
    //                   type: 'category',
    //                   label: 'Mechanics',
    //                   link: {
    //                     type: 'generated-index'
    //                   },
    //                   items: [
    //                     {
    //                       type: 'category',
    //                       type: 'autogenerated',
    //                       dirName: 'questions/who/chapters/chapter-2/mechanics'
    //                     }
    //                   ]
    //                 },
    //                 'questions/who/chapters/chapter-2/lingering-questions',
    //                 'questions/who/chapters/chapter-2/journal-entries'
    //               ]
    //             },
    //             {
    //               type: 'category',
    //               label: 'Chapter 3',
    //               link: {
    //                 type: 'generated-index'
    //               },
    //               items: [
    //                 {
    //                   type: 'category',
    //                   label: 'Milestones',
    //                   link: {
    //                     type: 'generated-index'
    //                   },
    //                   items: [
    //                     {
    //                       type: 'category',
    //                       type: 'autogenerated',
    //                       dirName: 'questions/who/chapters/chapter-3/milestones'
    //                     }
    //                   ]
    //                 },
    //                 {
    //                   type: 'category',
    //                   label: 'Mechanics',
    //                   link: {
    //                     type: 'generated-index'
    //                   },
    //                   items: [
    //                     {
    //                       type: 'category',
    //                       type: 'autogenerated',
    //                       dirName: 'questions/who/chapters/chapter-3/mechanics'
    //                     }
    //                   ]
    //                 },
    //                 'questions/who/chapters/chapter-3/searching-for-secrets',
    //                 'questions/who/chapters/chapter-3/journal-entries',
    //                 'questions/who/chapters/chapter-3/undead-nightmare'
    //               ]
    //             },
    //             {
    //               type: 'category',
    //               label: 'Chapter 4',
    //               link: {
    //                 type: 'generated-index'
    //               },
    //               items: [
    //                 {
    //                   type: 'category',
    //                   label: 'Milestones',
    //                   link: {
    //                     type: 'generated-index'
    //                   },
    //                   items: [
    //                     {
    //                       type: 'category',
    //                       type: 'autogenerated',
    //                       dirName: 'questions/who/chapters/chapter-4/milestones'
    //                     }
    //                   ]
    //                 },
    //                 {
    //                   type: 'category',
    //                   label: 'Mechanics',
    //                   link: {
    //                     type: 'generated-index'
    //                   },
    //                   items: [
    //                     {
    //                       type: 'category',
    //                       type: 'autogenerated',
    //                       dirName: 'questions/who/chapters/chapter-4/mechanics'
    //                     }
    //                   ]
    //                 },
    //                 'questions/who/chapters/chapter-4/inconvenient-truths',
    //                 'questions/who/chapters/chapter-4/journal-entries',
    //                 'questions/who/chapters/chapter-4/wither-nightmare'
    //               ]
    //             },
    //             {
    //               type: 'category',
    //               label: 'Chapter 5.1',
    //               link: {
    //                 type: 'generated-index'
    //               },
    //               items: [
    //                 {
    //                   type: 'category',
    //                   label: 'Milestones',
    //                   link: {
    //                     type: 'generated-index'
    //                   },
    //                   items: [
    //                     {
    //                       type: 'category',
    //                       type: 'autogenerated',
    //                       dirName: 'questions/who/chapters/chapter-5-1/milestones'
    //                     }
    //                   ]
    //                 },
    //                 {
    //                   type: 'category',
    //                   label: 'Mechanics',
    //                   link: {
    //                     type: 'generated-index'
    //                   },
    //                   items: [
    //                     {
    //                       type: 'category',
    //                       type: 'autogenerated',
    //                       dirName: 'questions/who/chapters/chapter-5-1/mechanics'
    //                     }
    //                   ]
    //                 },
    //                 'questions/who/chapters/chapter-5-1/path-of-preservation',
    //                 'questions/who/chapters/chapter-5-1/journal-entries'
    //               ]
    //             },
    //             {
    //               type: 'category',
    //               label: 'Chapter 5.2',
    //               link: {
    //                 type: 'generated-index'
    //               },
    //               items: [
    //                 {
    //                   type: 'category',
    //                   label: 'Milestones',
    //                   link: {
    //                     type: 'generated-index'
    //                   },
    //                   items: [
    //                     {
    //                       type: 'category',
    //                       type: 'autogenerated',
    //                       dirName: 'questions/who/chapters/chapter-5-2/milestones'
    //                     }
    //                   ]
    //                 },
    //                 {
    //                   type: 'category',
    //                   label: 'Mechanics',
    //                   link: {
    //                     type: 'generated-index'
    //                   },
    //                   items: [
    //                     {
    //                       type: 'category',
    //                       type: 'autogenerated',
    //                       dirName: 'questions/who/chapters/chapter-5-2/mechanics'
    //                     }
    //                   ]
    //                 },
    //                 'questions/who/chapters/chapter-5-2/path-of-progress',
    //                 'questions/who/chapters/chapter-5-2/journal-entries'
    //               ]
    //             },
    //             {
    //               type: 'category',
    //               label: 'Chapter 6',
    //               link: {
    //                 type: 'generated-index'
    //               },
    //               items: [
    //                 {
    //                   type: 'category',
    //                   label: 'Milestones',
    //                   link: {
    //                     type: 'generated-index'
    //                   },
    //                   items: [
    //                     {
    //                       type: 'category',
    //                       type: 'autogenerated',
    //                       dirName: 'questions/who/chapters/chapter-6/milestones'
    //                     }
    //                   ]
    //                 },
    //                 {
    //                   type: 'category',
    //                   label: 'Mechanics',
    //                   link: {
    //                     type: 'generated-index'
    //                   },
    //                   items: [
    //                     {
    //                       type: 'category',
    //                       type: 'autogenerated',
    //                       dirName: 'questions/who/chapters/chapter-6/mechanics'
    //                     }
    //                   ]
    //                 },
    //                 'questions/who/chapters/chapter-6/the-dream',
    //                 'questions/who/chapters/chapter-6/journal-entries'
    //               ]
    //             },
    //             {
    //               type: 'category',
    //               label: 'Chapter 7.1',
    //               link: {
    //                 type: 'generated-index'
    //               },
    //               items: [
    //                 {
    //                   type: 'category',
    //                   label: 'Milestones',
    //                   link: {
    //                     type: 'generated-index'
    //                   },
    //                   items: [
    //                     {
    //                       type: 'category',
    //                       type: 'autogenerated',
    //                       dirName: 'questions/who/chapters/chapter-7-1/milestones'
    //                     }
    //                   ]
    //                 },
    //                 {
    //                   type: 'category',
    //                   label: 'Mechanics',
    //                   link: {
    //                     type: 'generated-index'
    //                   },
    //                   items: [
    //                     {
    //                       type: 'category',
    //                       type: 'autogenerated',
    //                       dirName: 'questions/who/chapters/chapter-7-1/mechanics'
    //                     }
    //                   ]
    //                 },
    //                 'questions/who/chapters/chapter-7-1/solarpunk-awakening',
    //                 'questions/who/chapters/chapter-7-1/journal-entries'
    //               ]
    //             },
    //             {
    //               type: 'category',
    //               label: 'Chapter 7.2',
    //               link: {
    //                 type: 'generated-index'
    //               },
    //               items: [
    //                 {
    //                   type: 'category',
    //                   label: 'Milestones',
    //                   link: {
    //                     type: 'generated-index'
    //                   },
    //                   items: [
    //                     {
    //                       type: 'category',
    //                       type: 'autogenerated',
    //                       dirName: 'questions/who/chapters/chapter-7-2/milestones'
    //                     }
    //                   ]
    //                 },
    //                 {
    //                   type: 'category',
    //                   label: 'Mechanics',
    //                   link: {
    //                     type: 'generated-index'
    //                   },
    //                   items: [
    //                     {
    //                       type: 'category',
    //                       type: 'autogenerated',
    //                       dirName: 'questions/who/chapters/chapter-7-2/mechanics'
    //                     }
    //                   ]
    //                 },
    //                 'questions/who/chapters/chapter-7-2/cyberpunk-slumber',
    //                 'questions/who/chapters/chapter-7-2/journal-entries'
    //               ]
    //             },
    //             {
    //               type: 'category',
    //               label: 'Chapter 8',
    //               link: {
    //                 type: 'generated-index'
    //               },
    //               items: [
    //                 {
    //                   type: 'category',
    //                   label: 'Milestones',
    //                   link: {
    //                     type: 'generated-index'
    //                   },
    //                   items: [
    //                     {
    //                       type: 'category',
    //                       type: 'autogenerated',
    //                       dirName: 'questions/who/chapters/chapter-8/milestones'
    //                     }
    //                   ]
    //                 },
    //                 {
    //                   type: 'category',
    //                   label: 'Mechanics',
    //                   link: {
    //                     type: 'generated-index'
    //                   },
    //                   items: [
    //                     {
    //                       type: 'category',
    //                       type: 'autogenerated',
    //                       dirName: 'questions/who/chapters/chapter-8/mechanics'
    //                     }
    //                   ]
    //                 },
    //                 'questions/who/chapters/chapter-8/ascension',
    //                 'questions/who/chapters/chapter-8/journal-entries'
    //               ]
    //             }
    //           ]
    //         },
    //         'questions/who/nightmares',
    //         'questions/who/dreams'
    //       ]
    //     },
    //     {
    //       type: 'category',
    //       label: 'What Happened?',
    //       link: {
    //         type: 'generated-index'
    //       },
    //       items: [
    //         {
    //           type: 'category',
    //           label: 'Strange Worlds',
    //           link: {
    //             type: 'generated-index'
    //           },
    //           items: [
    //             'questions/what/dimensions/overworld',
    //             'questions/what/dimensions/everbright',
    //             'questions/what/dimensions/undergarden',
    //             'questions/what/dimensions/everdawn',
    //             'questions/what/dimensions/twilight-forest',
    //             'questions/what/dimensions/nether',
    //             'questions/what/dimensions/bumblezone',
    //             'questions/what/dimensions/blueleaf'
    //           ]
    //         },
    //         'questions/what/lost-stories'
    //       ]
    //     },
    //     {
    //       type: 'category',
    //       label: 'Why Did You Survive?',
    //       link: {
    //         type: 'generated-index'
    //       },
    //       items: ["questions/why/the-billionaire's-dream", 'questions/why/wake-up', 'questions/why/stay-asleep']
    //     }
    //   ]
    // },
    // {
    //   type: 'category',
    //   label: 'Messages & Motivations',
    //   link: {
    //     type: 'generated-index'
    //   },
    //   items: [
    //     {
    //       type: 'category',
    //       label: 'Issues',
    //       link: {
    //         type: 'generated-index'
    //       },
    //       items: [{ type: 'category', type: 'autogenerated', dirName: 'messages/issues' }]
    //     },
    //     {
    //       type: 'category',
    //       label: 'Philosophy',
    //       link: {
    //         type: 'generated-index'
    //       },
    //       items: [{ type: 'category', type: 'autogenerated', dirName: 'messages/philosophy' }]
    //     },
    //     'messages/the-world-is-dying',
    //     'messages/but-its-not-too-late'
    //   ]
    // },
    // {
    //   type: 'category',
    //   label: 'The Future of IM',
    //   link: {
    //     type: 'generated-index'
    //   },
    //   items: [{ type: 'category', type: 'autogenerated', dirName: 'future' }]
    // }
  ]
}
